---
# tasks file for snow-acm
- name: Create change request
  servicenow.itsm.change_request:
    instance:
      host: "{{ snow_credentials.instance | default(snow_instance, true)}}" 
      username: "{{ snow_credentials.username | default(snow_username, true)}}"
      password: "{{ snow_credentials.password | default(snow_password, true)}}"

    type: standard
    state: new
    requested_by: admin
    short_description: Ticket created by the Ansible + RHACM integration.
    risk: low
    impact: low

    other:
      expected_start: 2022-12-12
  register: output
- debug:
    var: output
    verbosity: 2
