---
# tasks file for snow-acm
- name: Create change request
  servicenow.itsm.change_request:
    instance:
      host: "{{ snow_credentials.instance | default(snow_instance, true)}}" 
      username: "{{ snow_credentials.username | default(snow_username, true)}}"
      password: "{{ snow_credentials.password | default(snow_password, true)}}"

    type: standard
    state: new
    requested_by: admin
    short_description: A brief description of the change goes here.
    description: A whole description of the change goes here. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...
    priority: moderate
    risk: low
    impact: low

    other:
      expected_start: 2022-12-12
- debug:
    var: number
    verbosity: 2
